version: "2.0"

services: 
    projectcars-frontend: 
        build: ./projectcars-frontend
        volumes: 
            - "./projectcars-frontend:/app"
        tty: true
        ports:
            - "3000:3000"
        container_name: projectcars-frontend
    projectcars-db:
        image: "mysql:8"
        container_name: projectcars-db
        environment: 
            MYSQL_ROOT_PASSWORD: hackme
            MYSQL_DATABASE: "projectcars"
        volumes: 
            - "./dbdata:/var/lib/mysql"
        restart: always

networks: 
    default:
        external: 
            name: projectcars